#ifndef CSG_CLIENT_INCLUDE_TYPES_INPUT_H
#define CSG_CLIENT_INCLUDE_TYPES_INPUT_H

#include <stdint.h>
#define MAX_USERINPUT 16

typedef enum {
	USERINPUT_IGNORE = 0,
	USERINPUT_EVENT_VK,
	USERINPUT_EVENT_ASCII,
} USERINPUT_EVENT_TYPE;

typedef enum {
	USERINPUT_KEY_NONE  = 0x0000,

	USERINPUT_KEY_LEFT  = 0x0001,
	USERINPUT_KEY_UP    = 0x0002,
	USERINPUT_KEY_RIGHT = 0x0004,
	USERINPUT_KEY_DOWN  = 0x0008,

	USERINPUT_KEY_ENTER     = 0x0010,
	USERINPUT_KEY_BACKSPACE = 0x0020,
	USERINPUT_KEY_DELETE    = 0x0040,
	USERINPUT_KEY_ESCAPE    = 0x0080,
} USERINPUT_EVENT_KEYS;

typedef struct {
	uint8_t eventType;
	uint8_t eventKey;
} UserBuffer, *P_UserBuffer;

#endif // CSG_CLIENT_INCLUDE_TYPES_INPUT_H

